---
abstract: 'Perl extension for the automatic generation of LaTeX tables.'
author:
  - '<limaone@cpan.org>'
build_requires:
  File::Spec: 0
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LaTeX-Table
provides:
  LaTeX::Table:
    file: lib/LaTeX/Table.pm
    version: v1.0.5_99
  LaTeX::Table::Themes::Beamer:
    file: lib/LaTeX/Table/Themes/Beamer.pm
    version: v1.0.6
  LaTeX::Table::Themes::Booktabs:
    file: lib/LaTeX/Table/Themes/Booktabs.pm
    version: v1.0.6
  LaTeX::Table::Themes::Classic:
    file: lib/LaTeX/Table/Themes/Classic.pm
    version: v1.0.6
  LaTeX::Table::Themes::Modern:
    file: lib/LaTeX/Table/Themes/Modern.pm
    version: v1.0.6
  LaTeX::Table::Themes::ThemeI:
    file: lib/LaTeX/Table/Themes/ThemeI.pm
    version: v1.0.6
  LaTeX::Table::Types::Ctable:
    file: lib/LaTeX/Table/Types/Ctable.pm
    version: v1.0.6
  LaTeX::Table::Types::Longtable:
    file: lib/LaTeX/Table/Types/Longtable.pm
    version: v1.0.6
  LaTeX::Table::Types::Std:
    file: lib/LaTeX/Table/Types/Std.pm
    version: v1.0.6
  LaTeX::Table::Types::TypeI:
    file: lib/LaTeX/Table/Types/TypeI.pm
    version: v1.0.6
  LaTeX::Table::Types::Xtab:
    file: lib/LaTeX/Table/Types/Xtab.pm
    version: v1.0.6
recommends:
  Getopt::Long: 0
  LaTeX::Driver: 0
  LaTeX::Encode: 0
  Number::Format: 0
  Text::CSV: 0
  autodie: 0
requires:
  Carp: 0
  Cwd: 0
  English: 0
  Module::Pluggable: 0
  Moose: 0.76
  MooseX::FollowPBP: 0.03
  Scalar::Util: 0
  Template: 0
  perl: v5.8.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/lima1/p5-latex-table
version: v1.0.5_99
